import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'

// Supply a Playwright module path when it is installed outside this checkout.
const { chromium } = await import(process.argv[2] || 'playwright')
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const origin = process.env.UI_ORIGIN || 'http://127.0.0.1:3020'
const artifacts = new URL('../artifacts/ui/', import.meta.url)
await mkdir(artifacts, { recursive: true })
const errors = []
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1040 }, reducedMotion: 'reduce' })
  const page = await context.newPage()
  page.on('pageerror', (e) => errors.push(e.stack || e.message))
  const previewRequests = []
  page.on('request', (r) => { if (r.url().includes('supabase.co')) previewRequests.push(r.url()) })
  await page.goto(`${origin}/preview/`)
  await page.locator('.product-card').first().waitFor()
  await page.evaluate(() => Promise.all([...document.images].map((im) => im.decode().catch(() => {}))))
  assert.deepEqual(await page.evaluate(() => [...document.images].filter((im) => !im.complete || im.naturalWidth === 0).map((im) => im.src)), [], 'All preview images render')
  const count = await page.locator('.product-card').count()
  assert.ok(count >= 12, 'Preview catalogue is populated')
  await page.screenshot({ path: new URL('desktop.png', artifacts).pathname, fullPage: true })
  await page.screenshot({ path: new URL('desktop-viewport.png', artifacts).pathname })
  for (const width of [390, 320, 768, 1024, 1920]) {
    await page.setViewportSize({ width, height: width < 500 ? 844 : 1040 })
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No page overflow at ${width}px`)
    if (width === 390) {
      await page.screenshot({ path: new URL('mobile.png', artifacts).pathname, fullPage: true })
      await page.screenshot({ path: new URL('mobile-viewport.png', artifacts).pathname })
    }
  }
  if (process.argv.includes('--capture')) { console.log('Captured desktop and mobile previews'); }
  else {
    await page.setViewportSize({ width: 1440, height: 1040 })
    const first = page.locator('.product-card').first()
    await first.getByRole('button', { name: 'ADD +' }).click()
    await first.getByRole('button', { name: 'Add one', exact: true }).click()
    assert.match(await page.locator('.header-cart').innerText(), /2 items/)
    await page.reload()
    await page.locator('.product-card.in-basket').waitFor()
    assert.match(await page.locator('.header-cart').innerText(), /2 items/)
    await page.locator('.product-open').first().click()
    const dialog = page.getByRole('dialog')
    await dialog.waitFor()
    await page.keyboard.press('Tab')
    assert.ok(await page.evaluate(() => document.querySelector('dialog[open]').contains(document.activeElement)), 'Focus stays in product sheet')
    await page.keyboard.press('Escape')
    await dialog.waitFor({ state: 'hidden' })
    const limited = page.locator('.product-card').filter({ hasText: 'Potato Chips' })
    await limited.getByRole('button', { name: 'ADD +' }).click()
    await limited.getByRole('button', { name: 'Add one', exact: true }).click()
    assert.ok(await limited.getByRole('button', { name: 'No more in stock' }).isDisabled())
    await limited.getByRole('button', { name: 'Remove one' }).click()
    await limited.getByRole('button', { name: 'Remove one' }).click()
    await page.getByLabel('In stock only').check()
    assert.equal(await page.locator('.product-card').count(), count - 1)
    await page.getByLabel('In stock only').uncheck()
    await page.getByLabel('Sort products').selectOption('price-low')
    const prices = await page.locator('.product-purchase strong').allTextContents()
    const numeric = prices.map((p) => Number(p.replace(/[^0-9.]/g, '')))
    assert.deepEqual(numeric, [...numeric].sort((a, b) => a - b))
    await page.locator('.header-search input').fill('rice')
    await page.locator('.header-search input').press('Enter')
    await page.waitForURL('**/search?q=rice')
    await page.locator('.product-card').first().waitFor()
    assert.ok((await page.locator('.product-card h3').allTextContents()).every((name) => /rice/i.test(name)))
    await page.locator('.header-cart').click()
    await page.waitForURL('**/cart')
    await page.setViewportSize({ width: 320, height: 740 })
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Basket fits small phones')
    await page.setViewportSize({ width: 1440, height: 1040 })
    await page.screenshot({ path: new URL('basket.png', artifacts).pathname, fullPage: true })
    await page.getByRole('button', { name: /Proceed|Continue to checkout/ }).click()
    await page.waitForURL('**/checkout')
    await page.getByRole('heading', { name: 'This is a sample basket' }).waitFor()
    assert.equal(previewRequests.length, 0, 'Preview makes no Supabase requests')
    const live = await context.newPage()
    live.on('pageerror', (e) => errors.push(e.message))
    await live.goto(origin)
    await live.locator('.product-card').first().waitFor({ timeout: 25000 })
    await live.screenshot({ path: new URL('live.png', artifacts).pathname, fullPage: true })
    assert.equal(await live.locator('.preview-notice').count(), 0)
    assert.equal(await live.locator('.product-card.in-basket').count(), 0, 'Preview cart is isolated')
    await live.goto(`${origin}/admin`)
    await live.getByRole('heading', { name: 'Welcome to your store' }).waitFor()
    await live.setViewportSize({ width: 390, height: 844 })
    assert.ok(await live.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Staff sign-in fits phones')
    await live.goto(`${origin}/rider`)
    await live.getByRole('heading', { name: 'Welcome to your store' }).waitFor()
    console.log('PASS: responsive layout, catalogue, basket persistence, product sheet, focus, filters, sorting, search, checkout guard, preview isolation, live catalogue')
  }
  assert.deepEqual(errors, [], 'No browser runtime errors')
} finally { await browser.close() }
